<?php

namespace Database\Seeders;

use App\Models\Dress;
use Illuminate\Database\Seeder;

class DressSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $rows = [
            [
                'id' => 'd1',
                'title' => 'Silk Column Gown - Champagne',
                'description' => 'Bias-cut silk with a subtle train. Perfect for black-tie and galas.',
                'image_urls' => [
                    'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=900&q=80',
                    'https://images.unsplash.com/photo-1515372039744-b8f02a3cd446?w=900&q=80',
                ],
                'sizes' => ['XS', 'S', 'M'],
                'colors' => ['Champagne', 'Ivory'],
                'occasion' => 'gala',
                'condition' => 'likeNew',
                'seller_type' => 'store',
                'rent_price' => 189,
                'buy_price' => 1280,
                'listing_mode' => 'both',
                'store_id' => 'st_velvet',
                'popularity_score' => 98,
                'created_at' => '2025-11-02 00:00:00',
            ],
            [
                'id' => 'd2',
                'title' => 'Sequin Mermaid Dress',
                'description' => 'High-impact sequins with structured bodice.',
                'image_urls' => [
                    'https://images.unsplash.com/photo-1566174053879-31528523f45e?w=900&q=80',
                ],
                'sizes' => ['S', 'M', 'L'],
                'colors' => ['Rose Gold'],
                'occasion' => 'prom',
                'condition' => 'excellent',
                'seller_type' => 'individual',
                'rent_price' => 95,
                'buy_price' => 420,
                'listing_mode' => 'both',
                'individual_seller_name' => 'Amelia K.',
                'seller_email' => 'amelia.k.closet@example.com',
                'seller_phone' => '+1 (917) 555-1130',
                'seller_location' => 'Upper East Side, Manhattan, NY - pickup by arrangement',
                'popularity_score' => 76,
                'created_at' => '2025-12-10 00:00:00',
            ],
            [
                'id' => 'd3',
                'title' => 'Minimal Slip - Noir',
                'description' => 'Clean lines, satin finish, adjustable straps.',
                'image_urls' => [
                    'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=900&q=80',
                ],
                'sizes' => ['XS', 'S', 'M', 'L'],
                'colors' => ['Black'],
                'occasion' => 'cocktail',
                'condition' => 'brandNew',
                'seller_type' => 'store',
                'rent_price' => 72,
                'buy_price' => 540,
                'listing_mode' => 'rent',
                'store_id' => 'st_lune',
                'popularity_score' => 88,
                'created_at' => '2025-10-05 00:00:00',
            ],
            [
                'id' => 'd4',
                'title' => 'Garden Wedding Lace',
                'description' => 'Romantic lace overlay with soft lining.',
                'image_urls' => [
                    'https://images.unsplash.com/photo-1519741497674-611481863552?w=900&q=80',
                ],
                'sizes' => ['S', 'M'],
                'colors' => ['Blush', 'Ivory'],
                'occasion' => 'wedding',
                'condition' => 'excellent',
                'seller_type' => 'store',
                'rent_price' => 210,
                'buy_price' => 1890,
                'listing_mode' => 'both',
                'store_id' => 'st_aurora',
                'popularity_score' => 91,
                'created_at' => '2025-09-18 00:00:00',
            ],
            [
                'id' => 'd5',
                'title' => 'Velvet Wrap Midi',
                'description' => 'Plush velvet with wrap waist - party ready.',
                'image_urls' => [
                    'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=900&q=80',
                ],
                'sizes' => ['XS', 'S', 'M'],
                'colors' => ['Emerald'],
                'occasion' => 'holiday',
                'condition' => 'good',
                'seller_type' => 'individual',
                'rent_price' => 58,
                'buy_price' => 260,
                'listing_mode' => 'buy',
                'individual_seller_name' => 'Sofia R.',
                'seller_email' => 'sofia.r.dresses@example.com',
                'seller_phone' => '+1 (310) 555-8841',
                'seller_location' => 'Santa Monica, CA - local meetup preferred',
                'popularity_score' => 54,
                'created_at' => '2025-08-22 00:00:00',
            ],
            [
                'id' => 'd6',
                'title' => 'Architectural Cape Gown',
                'description' => 'Sculptural cape sleeves, matte crepe.',
                'image_urls' => [
                    'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=900&q=80',
                ],
                'sizes' => ['S', 'M'],
                'colors' => ['Ivory'],
                'occasion' => 'gala',
                'condition' => 'likeNew',
                'seller_type' => 'store',
                'rent_price' => 245,
                'buy_price' => 2200,
                'listing_mode' => 'both',
                'store_id' => 'st_noir',
                'popularity_score' => 99,
                'created_at' => '2025-12-01 00:00:00',
            ],
            [
                'id' => 'd7',
                'title' => 'Satin Bias Midi',
                'description' => 'Effortless drape for date nights and cocktails.',
                'image_urls' => [
                    'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=900&q=80',
                ],
                'sizes' => ['XS', 'S', 'M', 'L'],
                'colors' => ['Copper'],
                'occasion' => 'dateNight',
                'condition' => 'excellent',
                'seller_type' => 'store',
                'rent_price' => 68,
                'buy_price' => 395,
                'listing_mode' => 'both',
                'store_id' => 'st_lune',
                'popularity_score' => 72,
                'created_at' => '2025-07-14 00:00:00',
            ],
            [
                'id' => 'd8',
                'title' => 'Feather Hem Mini',
                'description' => 'Playful feather trim - statement piece.',
                'image_urls' => [
                    'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=900&q=80',
                ],
                'sizes' => ['S', 'M'],
                'colors' => ['Black'],
                'occasion' => 'party',
                'condition' => 'good',
                'seller_type' => 'individual',
                'rent_price' => 110,
                'buy_price' => 0,
                'listing_mode' => 'rent',
                'individual_seller_name' => 'Jordan T.',
                'seller_email' => 'jordan.t.style@example.com',
                'seller_phone' => '+1 (404) 555-2290',
                'seller_location' => 'Midtown Atlanta, GA',
                'popularity_score' => 63,
                'created_at' => '2025-11-28 00:00:00',
            ],
            [
                'id' => 'd9',
                'title' => 'Pearl-Embellished Sheath',
                'description' => 'Hand-applied pearl clusters along neckline.',
                'image_urls' => [
                    'https://images.unsplash.com/photo-1583496661160-fb5886a0aa0b?w=900&q=80',
                ],
                'sizes' => ['M', 'L'],
                'colors' => ['Pearl White'],
                'occasion' => 'wedding',
                'condition' => 'brandNew',
                'seller_type' => 'store',
                'rent_price' => 265,
                'buy_price' => 2400,
                'listing_mode' => 'both',
                'store_id' => 'st_aurora',
                'popularity_score' => 85,
                'created_at' => '2025-06-03 00:00:00',
            ],
            [
                'id' => 'd10',
                'title' => 'Metallic Pleated Gown',
                'description' => 'Fluid pleats catch the light - red carpet energy.',
                'image_urls' => [
                    'https://images.unsplash.com/photo-1564859228278-91c5f2c5c4d8?w=900&q=80',
                ],
                'sizes' => ['XS', 'S', 'M'],
                'colors' => ['Bronze'],
                'occasion' => 'gala',
                'condition' => 'excellent',
                'seller_type' => 'store',
                'rent_price' => 198,
                'buy_price' => 1650,
                'listing_mode' => 'rent',
                'store_id' => 'st_velvet',
                'popularity_score' => 92,
                'created_at' => '2025-05-20 00:00:00',
            ],
            [
                'id' => 'd11',
                'title' => 'Brunch Linen Shirt Dress',
                'description' => 'Relaxed tailoring - elevated daytime.',
                'image_urls' => [
                    'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=900&q=80',
                ],
                'sizes' => ['S', 'M', 'L'],
                'colors' => ['Sand'],
                'occasion' => 'brunch',
                'condition' => 'likeNew',
                'seller_type' => 'individual',
                'rent_price' => 42,
                'buy_price' => 180,
                'listing_mode' => 'both',
                'individual_seller_name' => 'Priya N.',
                'seller_email' => 'priya.n.fashion@example.com',
                'seller_phone' => '+1 (206) 555-4412',
                'seller_location' => 'Capitol Hill, Seattle, WA',
                'popularity_score' => 41,
                'created_at' => '2025-04-08 00:00:00',
            ],
            [
                'id' => 'd12',
                'title' => 'Corset Ball Gown',
                'description' => 'Dramatic volume with structured bodice.',
                'image_urls' => [
                    'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=900&q=80',
                ],
                'sizes' => ['S', 'M'],
                'colors' => ['Midnight'],
                'occasion' => 'prom',
                'condition' => 'excellent',
                'seller_type' => 'store',
                'rent_price' => 320,
                'buy_price' => 2800,
                'listing_mode' => 'both',
                'store_id' => 'st_noir',
                'popularity_score' => 100,
                'created_at' => '2025-12-15 00:00:00',
            ],
        ];

        foreach ($rows as $row) {
            Dress::query()->create($row);
        }
    }
}
